-- FOREIGN KEY
CREATE TABLE A(
	NUM NUMBER(5) PRIMARY KEY,
	SDATA VARCHAR2(300)
); -- 부모테이블
DROP TABLE A;
CREATE TABLE B(
	DATA1 VARCHAR2(300),
	DATA2 VARCHAR2(300),
	NUM NUMBER(5),
	CONSTRAINT FK_TEST FOREIGN KEY(NUM) REFERENCES A(NUM)
	--			        자기 테이블NUM        상태 테이블 NUM
	--    			보통  PRIMARY KEY가  FOREIGN KEY가 된다 
	--				왜냐면  FOREIGN KEY키는 상대 테이블에 하나만 있어야 하기(중복이 되지 않아야) 때문이다.
); -- 자식 테이블
DROP TABLE B;

--- 수강신청 실습
--
CREATE TABLE STUDENT( -- 학생의 관한 정보만 담는 공간
-- NUM 과 JUMIN의 가장 큰 차이는 JUMIN은 원래 사람마다 다르게 부여되어있는거라 넣을 때만 오류가 생기지 않게 넣으면 되는거다. 
-- 그런데 NUM은 만들어 져 있는게 아니라 학생들을 구분하기 위해 기준으로 넣어 놓은 거기 때문에 특별하게 기본키여야 하는 것이다. 의미 차이 기억하자.
	NUM NUMBER(4) PRIMARY KEY ,
	JUMIN CHAR(13) UNIQUE , -- 유니크는 기본키와 다르게 실수가 나지 않도록 거는 제약
	NAME VARCHAR2(100) NOT NULL, -- 중복은 가능하나 비어있으면 안된다. PK 나 FK랑 다르게 유니크와 낫 널은 그냥 잘못넣지 않게 거는  제약 조건 일 뿐이므로 CONSTRAINT 가 필요없이 이렇게 적으면 된다.
	AGE NUMBER(3),
	MAJOR VARCHAR2(100),
	ADDR VARCHAR2(100)
);
CREATE TABLE SUBJECT( -- 수업에 관한 정보만 담는 공간 
	NAME VARCHAR(300) NOT NULL,
	DEPT VARCHAR(300),
	PROF VARCHAR(300) NOT NULL,
	MAXSTU NUMBER(2),
	CODE NUMBER(4) PRIMARY KEY -- 사실 CODE 나 NUM은 PK로 쓰기 위해 구분을 위해 만든 것이다. PK 선택하는 법 알겠지??
);
ALTER TABLE SUBJECT RENAME COLUMN PROFNUM TO NUM;
ALTER TABLE SUBJECT ADD CONSTRAINT SUB_PROF_FK
FOREIGN KEY(NUM) REFERENCES PROFESSOR(NUM);

CREATE TABLE PROFESSOR(
	NUM VARCHAR2(300) PRIMARY KEY,
	NAME VARCHAR2(200),
	DEPT VARCHAR2(100)
);

CREATE TABLE LIST( -- 어떤 학생이 어떤 수업을 신청 했는지 신청에대한 정보만 담는 공간
	NUM NUMBER(4),
	CODE NUMBER(4),
	CONSTRAINT  LIST_STU_FK FOREIGN KEY(NUM) REFERENCES STUDENT(NUM),
	CONSTRAINT  LIST_SUB_FK FOREIGN KEY(CODE) REFERENCES SUBJECT(CODE)
);

CREATE TABLE TEST3(
	GENDER CHAR(1) CHECK(GENDER IN ('M','W')), -- 체크 제약 조건 M 이나 W 가 아니면 오류가 난다.
	NUMDATA NUMBER(2) CHECK(NUMDATA>=10 AND NUMDATA <=90),
	STRDATA VARCHAR2(300) DEFAULT 'DEFAULT VALUE'
);
DROP TABLE TEST3;

-- K리그 축구경기 일정 관리 프로그램.
CREATE TABLE TEAM(
	TEAM VARCHAR(300),
	GRADE NUMBER(1) UNIQUE,
	TID NUMBER(2) PRIMARY KEY
);

CREATE TABLE SUNSU(
	NAME VARCHAR(300) NOT NULL,
	PID NUMBER(2) PRIMARY KEY,
	MGR VARCHAR(300),
	TID NUMBER(2) NOT NULL,
	CONSTRAINT T_FK FOREIGN KEY(TID) REFERENCES TEAM(TID)
);
CREATE TABLE SCHEDUE(
	DAT DATE,
	T1ID NUMBER(2),
	T2ID NUMBER(2),
	SID VARCHAR2(300),
	CONSTRAINT T1_FK FOREIGN KEY(T1ID) REFERENCES TEAM(TID),
	CONSTRAINT T2_FK FOREIGN KEY(T2ID) REFERENCES TEAM(TID),
	CONSTRAINT S_FK FOREIGN KEY(SID) REFERENCES STADIUM(SID)
);

CREATE TABLE STADIUM(
	SID VARCHAR2(300) PRIMARY KEY,
	SSEAT NUMBER(6) CHECK(SSEAT>0)
);









