--VIEW
CREATE VIEW NOT_K05 AS (SELECT PLAYER_ID,PLAYER_NAME, TEAM_ID, "POSITION" FROM PLAYER WHERE TEAM_ID != 'K05');
SELECT * FROM NOT_K05 WHERE "POSITION" ='MF';
DROP VIEW NOT_K05;

-- TABLE 서브쿼리로 만들기
CREATE TABLE NOT_K05 AS (SELECT PLAYER_ID,PLAYER_NAME, TEAM_ID, "POSITION" FROM PLAYER WHERE TEAM_ID != 'K05');
DROP TABLE NOT_K05;

--INSERT 여러개 하기
CREATE TABLE EMP_A (
	EMP_NUM NUMBER,
	EMP_NAME VARCHAR2(300)
);
CREATE TABLE EMP_B (
	EMP_NUM NUMBER,
	EMP_NAME VARCHAR2(300)
);
INSERT ALL
	INTO EMP_A VALUES('101','이순신')
	INTO EMP_B VALUES('101','아이언맨')
SELECT * FROM DUAL; -- INSERT ALL 하려면 의미 없는 서브 쿼리가 필요하다.
INSERT ALL
	INTO EMP_A VALUES('102','홍길동')
	INTO EMP_B VALUES('102','캡틴')
SELECT * FROM DUAL;
-- 다른 테이블 내용 복사해서 추가
INSERT INTO EMP_A (SELECT * FROM EMP_B); -- EMP_B에 있는게 전부 EMP_A로 들어가진다.
SELECT * FROM EMP_A;
-- 만일 자기 꺼에서 복사하면 내용이 2배로 늘어난다.
DROP TABLE EMP_A;
DROP TABLE EMP_B;

-- ALL
--SELECT * FROM EMP WHERE SAL >= (SELECT MAX(SAL) FROM EMP); --> 이거와 똑같은 내용이다.
SELECT HEIGHT FROM PLAYER;
SELECT * FROM EMP WHERE SAL >= ALL(SELECT SAL FROM EMP); -- 최대값보다 크거나 같은 값이니까 1개만 나온다.

--ANY
SELECT * FROM EMP WHERE SAL> ANY(SELECT SAL FROM EMP);

--T_EMP2에서 과장직급의 최소연봉자보다 급여를 더 받는 직원의
-- 이름, 직급 급여 검색
SELECT NAME 이름, POST 직급, PAY 급여 FROM T_EMP2
WHERE PAY > ANY(SELECT PAY FROM T_EMP2 WHERE POST = '과장')

--학생들 중 4학년의 최소 몸무게 보다 덜 나가는 학생의
-- 이름 학년 몸무게 검색
SELECT NAME 이름, GRADE 학년, WEIGHT 몸무게 FROM T_STUDENT
WHERE WEIGHT < ALL(SELECT WEIGHT FROM T_STUDENT WHERE GRADE=4);

--EXISTS
SELECT * FROM PLAYER
WHERE EXISTS(SELECT TEAM_ID FROM PLAYER WHERE TEAM_ID='K04'); 
-- WHERE절 뒤에가 참이 되면서 WHERE절이 없는 거 처럼 그냥 전부 다 나오게 된다, 대신 EXISTS 뒤에가 아무것도 없어서 거짓이 나오면 아무것도 안나오게 된다.
-- 따라서 EXISTS는 진짜 뒤에가 있는지 없는지만 확인할 때 그럴때만 사용한다.
SELECT * FROM PLAYER
WHERE TEAM_ID IN (SELECT TEAM_ID FROM PLAYER WHERE TEAM_ID='K04');

































